//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("InCommon")]
[assembly: System.Reflection.AssemblyVersion("13.3.10.0")]
[assembly: System.Reflection.AssemblyFileVersion("13.3.10.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyTitle("InCert")]
[assembly: System.Reflection.AssemblyProduct("InCert")]


