//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.InCommon.InCert.BootstrapperEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Org.InCommon.InCert.BootstrapperEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {0} installer!.
        /// </summary>
        internal static string AbsentText {
            get {
                return ResourceManager.GetString("AbsentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling {0} installation.
        /// </summary>
        internal static string CancellingInstallText {
            get {
                return ResourceManager.GetString("CancellingInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling {0} removal.
        /// </summary>
        internal static string CancellingRemoveText {
            get {
                return ResourceManager.GetString("CancellingRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling {0} repair.
        /// </summary>
        internal static string CancellingRepairText {
            get {
                return ResourceManager.GetString("CancellingRepairText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling {0} update.
        /// </summary>
        internal static string CancellingUpdateText {
            get {
                return ResourceManager.GetString("CancellingUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling operation.
        /// </summary>
        internal static string GenericCancellingText {
            get {
                return ResourceManager.GetString("GenericCancellingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing installer.
        /// </summary>
        internal static string InitializingText {
            get {
                return ResourceManager.GetString("InitializingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click start to launch {0}!.
        /// </summary>
        internal static string InstalledStartText {
            get {
                return ResourceManager.GetString("InstalledStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue occurred while installing {0}:{1}{2} ({3}).
        /// </summary>
        internal static string InstallErrorText {
            get {
                return ResourceManager.GetString("InstallErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}.
        /// </summary>
        internal static string InstallingText {
            get {
                return ResourceManager.GetString("InstallingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of {0} is already installed on this computer.
        ///
        ///This version cannot be installed until the newer version has been removed..
        /// </summary>
        internal static string NewerText {
            get {
                return ResourceManager.GetString("NewerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click start to launch {0}!.
        /// </summary>
        internal static string PresentText {
            get {
                return ResourceManager.GetString("PresentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click start to launch {0}!.
        /// </summary>
        internal static string RepairedText {
            get {
                return ResourceManager.GetString("RepairedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue occurred while repairing {0}:{1}{2} ({3}).
        /// </summary>
        internal static string RepairErrorText {
            get {
                return ResourceManager.GetString("RepairErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing {0}.
        /// </summary>
        internal static string RepairingText {
            get {
                return ResourceManager.GetString("RepairingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully removed!.
        /// </summary>
        internal static string UinstalledText {
            get {
                return ResourceManager.GetString("UinstalledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue occurred while removing {0}:{1}{2} ({3}).
        /// </summary>
        internal static string UninstallErrorText {
            get {
                return ResourceManager.GetString("UninstallErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0}.
        /// </summary>
        internal static string UninstallingText {
            get {
                return ResourceManager.GetString("UninstallingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully updated!.
        /// </summary>
        internal static string UpdatedText {
            get {
                return ResourceManager.GetString("UpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue occurred while updating {0}:{1}{2} ({3}).
        /// </summary>
        internal static string UpdateErrorText {
            get {
                return ResourceManager.GetString("UpdateErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}.
        /// </summary>
        internal static string UpdatingText {
            get {
                return ResourceManager.GetString("UpdatingText", resourceCulture);
            }
        }
    }
}
